#!/usr/bin/env bash
#
# Change VAULT to the location of the vault password file 
# Vault password is not required for dev VMs.
#
VAULT=~/.hisparc_vault
if [ -f "$VAULT" ]; then
	cat $VAULT
else
	echo "This is not the vault password!"
fi
