# Generated by Django 3.2.15 on 2024-03-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inforecords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationLayoutQuarantine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('hash_submit', models.CharField(max_length=32)),
                ('hash_review', models.CharField(max_length=32)),
                ('active_date', models.DateTimeField()),
                ('detector_1_radius', models.FloatField()),
                ('detector_1_alpha', models.FloatField()),
                ('detector_1_height', models.FloatField()),
                ('detector_1_beta', models.FloatField()),
                ('detector_2_radius', models.FloatField()),
                ('detector_2_alpha', models.FloatField()),
                ('detector_2_height', models.FloatField()),
                ('detector_2_beta', models.FloatField()),
                ('detector_3_radius', models.FloatField(blank=True, null=True)),
                ('detector_3_alpha', models.FloatField(blank=True, null=True)),
                ('detector_3_height', models.FloatField(blank=True, null=True)),
                ('detector_3_beta', models.FloatField(blank=True, null=True)),
                ('detector_4_radius', models.FloatField(blank=True, null=True)),
                ('detector_4_alpha', models.FloatField(blank=True, null=True)),
                ('detector_4_height', models.FloatField(blank=True, null=True)),
                ('detector_4_beta', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantined_layouts', to='inforecords.station')),
            ],
            options={
                'verbose_name': 'Station layout quarantine',
                'verbose_name_plural': 'Station layouts quarantine',
            },
        ),
        migrations.CreateModel(
            name='StationLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_date', models.DateTimeField()),
                ('detector_1_radius', models.FloatField()),
                ('detector_1_alpha', models.FloatField()),
                ('detector_1_height', models.FloatField()),
                ('detector_1_beta', models.FloatField()),
                ('detector_2_radius', models.FloatField()),
                ('detector_2_alpha', models.FloatField()),
                ('detector_2_height', models.FloatField()),
                ('detector_2_beta', models.FloatField()),
                ('detector_3_radius', models.FloatField(blank=True, null=True)),
                ('detector_3_alpha', models.FloatField(blank=True, null=True)),
                ('detector_3_height', models.FloatField(blank=True, null=True)),
                ('detector_3_beta', models.FloatField(blank=True, null=True)),
                ('detector_4_radius', models.FloatField(blank=True, null=True)),
                ('detector_4_alpha', models.FloatField(blank=True, null=True)),
                ('detector_4_height', models.FloatField(blank=True, null=True)),
                ('detector_4_beta', models.FloatField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='inforecords.station')),
            ],
            options={
                'verbose_name': 'Station layout',
                'verbose_name_plural': 'Station layouts',
                'ordering': ['station', 'active_date'],
                'get_latest_by': 'active_date',
                'unique_together': {('station', 'active_date')},
            },
        ),
    ]
