# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_layout', '0002_alter_meta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationlayoutquarantine',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
