# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-20 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station_layout', '0004_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationlayout',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='inforecords.Station'),
        ),
        migrations.AlterField(
            model_name='stationlayoutquarantine',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarantined_layouts', to='inforecords.Station'),
        ),
    ]
