Vagrant.configure("1") do |config|

    # veewee source code for this box:
    # https://github.com/puppetlabs/puppet-vagrant-boxes/tree/master/definitions/centos-59-x64-vbox4210
    config.vm.box = 'centOS 5.9'
    config.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/centos-59-x64-vbox4210.box'
    
    config.vm.network :hostonly, "10.11.12.13"
    config.vm.network :bridged

    # Forward webserver to 8080
    config.vm.forward_port 80, 8080
    # Forwarding MySQL
    config.vm.forward_port 3306, 3306

    # Share the publicdb repository with the virtual box to test it
    config.vm.share_folder "Django", "/vagrant", ".."
    
    config.vm.provision :puppet do |puppet|
        puppet.manifests_path = "puppet/manifests"
        puppet.module_path = "puppet/modules"
    end

end
