# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-20 23:10
from __future__ import unicode_literals

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histograms', '0012_arrayfields_for_dailydataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationtimingoffset',
            name='ref_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_station_offsets', to='histograms.Summary'),
        ),
        migrations.AlterField(
            model_name='stationtimingoffset',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_offsets', to='histograms.Summary'),
        ),
    ]
