# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histograms', '0015_datasettype_has_multiple_datasets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulseheightfit',
            name='error_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pulseheightfit',
            name='error_type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='pulseheightfit',
            name='plate',
            field=models.IntegerField(choices=[(1, 'Scintillator 1'), (2, 'Scintillator 2'), (3, 'Scintillator 3'), (4, 'Scintillator 4')]),
        ),
    ]
