# Generated by Django 1.11.12 on 2018-07-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histograms', '0017_related_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'get_latest_by': 'timestamp', 'ordering': ['summary'], 'verbose_name': 'Configuration', 'verbose_name_plural': 'Configurations'},
        ),
        migrations.AlterModelOptions(
            name='dailydataset',
            options={'ordering': ['summary', 'type']},
        ),
        migrations.AlterModelOptions(
            name='dailyhistogram',
            options={'ordering': ['summary', 'type']},
        ),
        migrations.AlterModelOptions(
            name='detectortimingoffset',
            options={'ordering': ['summary'], 'verbose_name': 'Detector timing offset', 'verbose_name_plural': 'Detector timing offsets'},
        ),
        migrations.AlterModelOptions(
            name='multidailydataset',
            options={'ordering': ['summary', 'type']},
        ),
        migrations.AlterModelOptions(
            name='multidailyhistogram',
            options={'ordering': ['summary', 'type']},
        ),
        migrations.AlterModelOptions(
            name='networkhistogram',
            options={'ordering': ['network_summary', 'type'], 'verbose_name': 'Network histogram', 'verbose_name_plural': 'Network histograms'},
        ),
        migrations.AlterModelOptions(
            name='pulseheightfit',
            options={'ordering': ['summary', 'plate'], 'verbose_name': 'Pulseheight fit', 'verbose_name_plural': 'Pulseheight fits'},
        ),
        migrations.AlterModelOptions(
            name='stationtimingoffset',
            options={'ordering': ['ref_summary'], 'verbose_name': 'Station timing offset', 'verbose_name_plural': 'Station timing offsets'},
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='source',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='dailydataset',
            old_name='source',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='dailyhistogram',
            old_name='source',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='detectortimingoffset',
            old_name='source',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='multidailydataset',
            old_name='source',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='multidailyhistogram',
            old_name='source',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='networkhistogram',
            old_name='source',
            new_name='network_summary',
        ),
        migrations.RenameField(
            model_name='pulseheightfit',
            old_name='source',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='stationtimingoffset',
            old_name='ref_source',
            new_name='ref_summary',
        ),
        migrations.RenameField(
            model_name='stationtimingoffset',
            old_name='source',
            new_name='summary',
        ),
        migrations.AlterUniqueTogether(
            name='dailydataset',
            unique_together={('summary', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyhistogram',
            unique_together={('summary', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='multidailydataset',
            unique_together={('summary', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='multidailyhistogram',
            unique_together={('summary', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='networkhistogram',
            unique_together={('network_summary', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='pulseheightfit',
            unique_together={('summary', 'plate')},
        ),
        migrations.AlterUniqueTogether(
            name='stationtimingoffset',
            unique_together={('ref_summary', 'summary')},
        ),
    ]
