# Generated by Django 1.10.8 on 2018-07-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histograms', '0018_source_to_summary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pulseheightfit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pulseheightfit',
            name='summary',
        ),
        migrations.DeleteModel(
            name='PulseheightFit',
        ),
    ]
