# Generated by Django 1.11.20 on 2019-03-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histograms', '0019_remove_pulseheightfit'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='events_in_last_hour',
            field=models.BooleanField(default=False),
        ),
    ]
