#!/bin/sh

#
# Make a certificate/private key pair using a locally generated
# root certificate.
#
# DF: added -batch options (Tristan did in his inforecords view code).

if test $# -ne 1; then
        echo "usage: build-key <name>";
        exit 1
fi                                                                             

if test $KEY_DIR; then
	cd $KEY_DIR && \
	openssl req -days 3650 -nodes -new -keyout $1.key -out $1.csr -config $KEY_CONFIG -batch && \
	openssl ca -days 3650 -out $1.crt -in $1.csr -config $KEY_CONFIG -batch
	#chmod 0600 $1.key
else
	echo you must define KEY_DIR
fi
