# Generated by Django 3.2.15 on 2024-03-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('number', models.IntegerField(blank=True, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('prefix_surname', models.CharField(blank=True, max_length=255)),
                ('surname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['surname', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_1', models.CharField(max_length=255)),
                ('street_2', models.CharField(blank=True, max_length=255, null=True)),
                ('postalcode', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('pobox', models.CharField(blank=True, max_length=255, null=True)),
                ('pobox_postalcode', models.CharField(blank=True, max_length=255, null=True)),
                ('pobox_city', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_work', models.CharField(max_length=255)),
                ('phone_home', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('email_work', models.EmailField(max_length=254)),
                ('email_private', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact information',
                'verbose_name_plural': 'Contact information',
                'ordering': ['city', 'street_1', 'email_work'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('number', models.IntegerField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('info_page', models.TextField(blank=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='inforecords.cluster')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations_contact', to='inforecords.contact')),
                ('contactinformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='inforecords.contactinformation')),
                ('ict_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations_ict_contact', to='inforecords.contact')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Pc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_test', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, protocol='ipv4', unique=True)),
                ('notes', models.TextField(blank=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to='inforecords.station')),
            ],
            options={
                'verbose_name': 'PC',
                'verbose_name_plural': 'PCs',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='contactinformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='inforecords.contactinformation'),
        ),
        migrations.AddField(
            model_name='contact',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='inforecords.profession'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='inforecords.country'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subclusters', to='inforecords.cluster'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('first_name', 'prefix_surname', 'surname')},
        ),
    ]
