# Generated by Django 1.11.12 on 2018-07-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inforecords', '0008_contact_title_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ['name'], 'verbose_name': 'Cluster', 'verbose_name_plural': 'Clusters'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['surname', 'first_name'], 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'ordering': ['city', 'street_1', 'email_work'], 'verbose_name': 'Contact information', 'verbose_name_plural': 'Contact information'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['number'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='enabledservice',
            options={'ordering': ['pc', 'monitor_service'], 'verbose_name': 'Enabled Service', 'verbose_name_plural': 'Enabled Services'},
        ),
        migrations.AlterModelOptions(
            name='monitorpulseheightthresholds',
            options={'verbose_name': 'Pulseheight threshold for Nagios', 'verbose_name_plural': 'Pulseheight thresholds for Nagios'},
        ),
        migrations.AlterModelOptions(
            name='monitorservice',
            options={'ordering': ['description'], 'verbose_name': 'Monitor Service', 'verbose_name_plural': 'Monitor Services'},
        ),
        migrations.AlterModelOptions(
            name='pc',
            options={'ordering': ['name'], 'verbose_name': 'PC and certificates', 'verbose_name_plural': 'PCs and certificates'},
        ),
        migrations.AlterModelOptions(
            name='pctype',
            options={'verbose_name': 'PC Type', 'verbose_name_plural': 'PC Types'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Profession', 'verbose_name_plural': 'Professions'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['number'], 'verbose_name': 'Station', 'verbose_name_plural': 'Stations'},
        ),
    ]
