# Generated by Django 1.11.12 on 2018-07-20 00:57

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inforecords', '0009_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='inforecords.Profession'),
        ),
        migrations.AlterField(
            model_name='enabledservice',
            name='monitor_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_services', to='inforecords.MonitorService'),
        ),
        migrations.AlterField(
            model_name='enabledservice',
            name='pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enabled_services', to='inforecords.Pc'),
        ),
        migrations.AlterField(
            model_name='monitorpulseheightthresholds',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulsehieght_thresholds', to='inforecords.Station'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to='inforecords.Station'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcs', to='inforecords.PcType'),
        ),
    ]
