# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-22 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inforecords', '0010_related_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitorpulseheightthresholds',
            name='station',
        ),
        migrations.DeleteModel(
            name='MonitorPulseheightThresholds',
        ),
    ]
