# Generated by Django 3.2.14 on 2022-07-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inforecords', '0011_remove_pulseheightthresholds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='services',
        ),
        migrations.DeleteModel(
            name='EnabledService',
        ),
        migrations.DeleteModel(
            name='MonitorService',
        ),
    ]
