# Generated by Django 3.2.15 on 2024-03-29 19:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inforecords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coincidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('nanoseconds', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Coincidence',
                'verbose_name_plural': 'Coincidences',
                'ordering': ['date', 'time', 'nanoseconds'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('nanoseconds', models.IntegerField()),
                ('pulseheights', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=4)),
                ('integrals', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=4)),
                ('traces', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=4)),
                ('coincidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='coincidences.coincidence')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inforecords.station')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date', 'time', 'nanoseconds', 'station'],
            },
        ),
    ]
