# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-15 07:22
from __future__ import unicode_literals

import django.contrib.postgres.fields

from django.db import migrations, models

from sapphire.utils import pbar


def serialiseddatafield_to_arrayfield(apps, schema_editor):
    """Forwards migrations"""
    model = apps.get_model('coincidences', 'Event')
    print('')
    for event in pbar(model.objects.all().iterator(), length=model.objects.all().count()):
        event.pulseheights = event.old_pulseheights
        event.integrals = event.old_integrals
        event.traces = event.old_traces
        event.save()


def arrayfield_to_serialiseddatafield(apps, schema_editor):
    """Backwards migrations"""
    raise NotImplementedError


class Migration(migrations.Migration):

    dependencies = [
        ('coincidences', '0001_initial'),
    ]

    operations = [
        # Move old fields out of the way
        migrations.RenameField(
            model_name='event',
            old_name='pulseheights',
            new_name='old_pulseheights',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='integrals',
            new_name='old_integrals',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='traces',
            new_name='old_traces',
        ),
        # Add new fields, with null=True
        migrations.AddField(
            model_name='event',
            name='pulseheights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=4),
        ),
        migrations.AddField(
            model_name='event',
            name='integrals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=4),
        ),
        migrations.AddField(
            model_name='event',
            name='traces',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), null=True, size=4),
        ),
        # Move data into new fields
        migrations.RunPython(
            serialiseddatafield_to_arrayfield,
            arrayfield_to_serialiseddatafield,
            hints={'model_name': 'Event'}
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name='event',
            name='old_pulseheights',
        ),
        migrations.RemoveField(
            model_name='event',
            name='old_integrals',
        ),
        migrations.RemoveField(
            model_name='event',
            name='old_traces',
        ),
        # Make new fields non-nullable
        migrations.AlterField(
            model_name='event',
            name='pulseheights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='integrals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='traces',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=4),
        ),
    ]
