# Generated by Django 1.11.12 on 2018-07-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coincidences', '0004_m2m_to_foreignkey_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coincidence',
            options={'ordering': ['date', 'time', 'nanoseconds'], 'verbose_name': 'Coincidence', 'verbose_name_plural': 'Coincidences'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time', 'nanoseconds', 'station'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
