# Generated by Django 1.11.12 on 2018-07-20 00:57

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coincidences', '0005_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inforecords.Station'),
        ),
    ]
