# Generated by Django 3.2.15 on 2024-03-29 19:27

from django.db import migrations, models
import django.db.models.deletion
import publicdb.updates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('update', models.FileField(upload_to=publicdb.updates.models.upload_queue)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_updates', to='updates.updatequeue')),
            ],
            options={
                'verbose_name': 'User update',
                'verbose_name_plural': 'User updates',
                'ordering': ['-version'],
                'unique_together': {('queue', 'version')},
            },
        ),
        migrations.CreateModel(
            name='InstallerUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=5)),
                ('installer', models.FileField(upload_to=publicdb.updates.models.upload_queue)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installer_updates', to='updates.updatequeue')),
            ],
            options={
                'verbose_name': 'Installer update',
                'verbose_name_plural': 'Installer updates',
                'ordering': ['-version'],
                'unique_together': {('queue', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AdminUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField()),
                ('update', models.FileField(upload_to=publicdb.updates.models.upload_queue)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_updates', to='updates.updatequeue')),
            ],
            options={
                'verbose_name': 'Admin update',
                'verbose_name_plural': 'Admin updates',
                'ordering': ['-version'],
                'unique_together': {('queue', 'version')},
            },
        ),
    ]
