# Generated by Django 1.11.12 on 2018-07-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminupdate',
            options={'ordering': ['version'], 'verbose_name': 'Admin update', 'verbose_name_plural': 'Admin updates'},
        ),
        migrations.AlterModelOptions(
            name='installerupdate',
            options={'ordering': ['version'], 'verbose_name': 'Installer update', 'verbose_name_plural': 'Installer updates'},
        ),
        migrations.AlterModelOptions(
            name='userupdate',
            options={'ordering': ['version'], 'verbose_name': 'User update', 'verbose_name_plural': 'User updates'},
        ),
    ]
