# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-20 00:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminupdate',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_updates', to='updates.UpdateQueue'),
        ),
        migrations.AlterField(
            model_name='installerupdate',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installer_updates', to='updates.UpdateQueue'),
        ),
        migrations.AlterField(
            model_name='userupdate',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_updates', to='updates.UpdateQueue'),
        ),
    ]
