# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions

# Activate env
alias envpub='source activate /srv/publicdb/publicdb_env'
# Go to publicdb repository
alias cdpub='cd /srv/publicdb/www'
# Collect static files, and reload uwsgi
alias collectreload='envpub && cdpub && cd django_publicdb && ./manage.py collectstatic --noinput && touch /tmp/uwsgi-reload.me'

# Perform the daily hisparc-update task
alias uphis='envpub && cdpub && python scripts/hisparc-update.py >> /var/log/hisparc-update.log 2>&1'

# Update publicdb to latest master
alias uppub='envpub && cdpub && git fetch && git reset --hard origin/master && collectreload'
# Update jSparc to latest master
alias upjs='envpub && cdpub && cd ../jsparc && git fetch && git reset --hard origin/master'

# Dev: Update publicdb to local HEAD (only in VM!)
alias adddev='[[ -d /vagrant ]] && envpub && cdpub && git remote add local /vagrant/.git'
alias updev='[[ -d /vagrant ]] && envpub && cdpub && git fetch local && git reset --hard $(cd /vagrant; git rev-parse --verify HEAD) && collectreload'

# Prompt
[[ -n "$SSH_CLIENT" ]] && PS1='\[\e[1;30m\]$(date +%y%m%d\ %H:%M:%S) \[\e[1;32m\]\u@\h \[\e[1;34m\]\w\n$CONDA_DEFAULT_ENV\[\e[m\]> '
