# .bashrc for datastore

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$({{ miniconda_path }} 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "{{ miniconda_path }}/etc/profile.d/conda.sh" ]; then
        . "{{ miniconda_path }}/etc/profile.d/conda.sh"
    else
        export PATH="{{ miniconda_path }}/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

    
# Activate env
conda activate datastore_venv
alias envdata='conda activate {{ datastore_venv }}'

# Supervisor aliases
alias startsupd='supervisord -c {{ supervisord_path }}/supervisord.conf'
alias stopsupd='killall -w supervisord'
alias statussupd="if pgrep supervisord >/dev/null; then echo 'RUNNING'; else echo 'NOT RUNNING'; fi"
alias supctl='supervisorctl -c {{ supervisord_path }}/supervisord.conf'

# Go to datastore repository
alias cddata='cd {{ datastore_code }}'

# Reload web server
alias reload='touch /tmp/uwsgi-reload.me'

# Update datastore to latest master
alias updata='envdata && cddata && git fetch && git reset --hard origin/master && reload'
