# Generated by Django 3.2.15 on 2024-03-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coincidences', '0001_initial'),
        ('inforecords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('hash', models.CharField(max_length=32)),
                ('pin', models.CharField(max_length=4)),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Analysis session',
                'verbose_name_plural': 'Analysis sessions',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='analysissessions.analysissession')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('sur_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=255)),
                ('events_to_create', models.IntegerField()),
                ('events_created', models.IntegerField()),
                ('start_date', models.DateField()),
                ('mail_send', models.BooleanField(default=False)),
                ('session_confirmed', models.BooleanField(default=False)),
                ('session_pending', models.BooleanField(default=False)),
                ('session_created', models.BooleanField(default=False)),
                ('url', models.CharField(max_length=20)),
                ('sid', models.CharField(blank=True, max_length=255, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to='inforecords.cluster')),
            ],
            options={
                'verbose_name': 'Session request',
                'verbose_name_plural': 'Session requests',
            },
        ),
        migrations.CreateModel(
            name='AnalyzedCoincidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_analyzed', models.BooleanField(default=False)),
                ('core_position_x', models.FloatField(blank=True, null=True)),
                ('core_position_y', models.FloatField(blank=True, null=True)),
                ('log_energy', models.FloatField(blank=True, null=True)),
                ('theta', models.FloatField(blank=True, null=True)),
                ('phi', models.FloatField(blank=True, null=True)),
                ('error_estimate', models.FloatField(blank=True, null=True)),
                ('coincidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzed_coincidences', to='coincidences.coincidence')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyzed_coincidences', to='analysissessions.analysissession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_coincidences', to='analysissessions.student')),
            ],
            options={
                'verbose_name': 'Analyzed coincidence',
                'verbose_name_plural': 'Analyzed coincidences',
                'ordering': ['coincidence'],
            },
        ),
        migrations.AddField(
            model_name='analysissession',
            name='session_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysissessions.sessionrequest'),
        ),
    ]
