# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-05 23:13
from __future__ import unicode_literals

import django.db.models.deletion

from django.db import migrations, models


def forwards(apps, schema_editor):
    analysis_session_model = apps.get_model('analysissessions', 'AnalysisSession')
    session_request_model = apps.get_model('analysissessions', 'SessionRequest')

    # Match analysis sessions to session requests based on the title and sid.
    for analysis_session in analysis_session_model.objects.all():
        try:
            session_request = session_request_model.objects.get(sid=analysis_session.title)
        except session_request_model.DoesNotExist:
            # Could not find matching request, remove the session.
            analysis_session.delete()
        else:
            analysis_session.session_request = session_request
            analysis_session.save()


class Migration(migrations.Migration):

    dependencies = [
        ('analysissessions', '0003_on_delete_set_student_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='session_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysissessions.SessionRequest'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='analysissession',
            name='session_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysissessions.SessionRequest'),
        ),
    ]
