# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-05 23:13
from __future__ import unicode_literals

import django.db.models.deletion

from django.db import migrations, models


def forwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('analysissessions', '0003_on_delete_set_student_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='session_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysissessions.SessionRequest'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='analysissession',
            name='session_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysissessions.SessionRequest'),
        ),
    ]
