# Generated by Django 3.2.14 on 2022-07-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysissessions', '0006_related_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysissession',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='school',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='sur_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
